print("number of lives.")
lives = int(input())
print("please enter energy level")
energy = int(input())
print("please enter shiled level")
shield = int(input())
print(f"lives: {'♥' * lives}")
print(f"energy: {'♦' * energy}")
print(f"shield: {'♦' * shield}")